version: '3.1'

services:

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testpgdb
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test"]
      interval: 10s
      timeout: 5s
      retries: 5
